{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ibeilly",
    "module": "kyc-camerax",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "iudw3iwrrraitgovn2k7inm6mi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kyc-camerax-1.1.0.aar",
          "url": "kyc-camerax-1.1.0.aar",
          "size": 133245,
          "sha512": "9b3f42131aeeb9aa6435bd7b2f380924c4542f7cf69e72cb9cc8bf0e34fb534fd60f9acd2a24e9ccb540cfd5439a98856c4841ed8f9238a856a86e5454f652dd",
          "sha256": "83bb66d38e61891b1913e270c8604c69ca249a8f039165ce087b170f4be34da4",
          "sha1": "248ea92d445247cfb4e4f492e6ea8daa05e8349a",
          "md5": "e355eace8d6732ecfcf515f14767865f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha27"
          }
        }
      ],
      "files": [
        {
          "name": "kyc-camerax-1.1.0.aar",
          "url": "kyc-camerax-1.1.0.aar",
          "size": 133245,
          "sha512": "9b3f42131aeeb9aa6435bd7b2f380924c4542f7cf69e72cb9cc8bf0e34fb534fd60f9acd2a24e9ccb540cfd5439a98856c4841ed8f9238a856a86e5454f652dd",
          "sha256": "83bb66d38e61891b1913e270c8604c69ca249a8f039165ce087b170f4be34da4",
          "sha1": "248ea92d445247cfb4e4f492e6ea8daa05e8349a",
          "md5": "e355eace8d6732ecfcf515f14767865f"
        }
      ]
    }
  ]
}
