{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ibeilly",
    "module": "kyc-camerax",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cyb3zar6yfe65nnskdqyczxkiy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "kyc-camerax-1.0.0.aar",
          "url": "kyc-camerax-1.0.0.aar",
          "size": 135973,
          "sha512": "06712ad81dce776eab5b3759a21d7ae4e8669c8c2bda35da36a0d140ebc18489089a820a91274cd0a94096069ce494adad6349f60149da56ccf6f054faee2815",
          "sha256": "227c697a182e96916a102b0a6cd2b9a66a6c8c8ca3c0c58150ffa0fe8bdbafdb",
          "sha1": "8e0daa3f019a6c90f3cde42dab06bbdb7ef99eaa",
          "md5": "158e44645ff3bdf63aadbc4cce1b67c4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha27"
          }
        }
      ],
      "files": [
        {
          "name": "kyc-camerax-1.0.0.aar",
          "url": "kyc-camerax-1.0.0.aar",
          "size": 135973,
          "sha512": "06712ad81dce776eab5b3759a21d7ae4e8669c8c2bda35da36a0d140ebc18489089a820a91274cd0a94096069ce494adad6349f60149da56ccf6f054faee2815",
          "sha256": "227c697a182e96916a102b0a6cd2b9a66a6c8c8ca3c0c58150ffa0fe8bdbafdb",
          "sha1": "8e0daa3f019a6c90f3cde42dab06bbdb7ef99eaa",
          "md5": "158e44645ff3bdf63aadbc4cce1b67c4"
        }
      ]
    }
  ]
}
